# Generated by Django 4.2.2 on 2023-06-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('supplier', models.CharField(max_length=40)),
                ('supplierid', models.IntegerField()),
            ],
        ),
    ]
