# Generated by Django 4.2.2 on 2023-06-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='supplierid',
            field=models.CharField(max_length=20),
        ),
    ]
