# Generated by Django 4.2.2 on 2023-06-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPP', '0002_alter_products_supplierid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='pid',
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
